### ISSUE TITLE
코드 리뷰를 드립니다.

### ISSUE THREAD

**Issue by hyokualexkwon** [MyNameSieun/Todo-List#1]
안녕하세요? 과제 하느라 정말 수고 많으셨어요!

제가 코드를 보면서 개선되면 좋을것 같은 부분이나 궁금한 점들을 적어볼게요. 다만, 글로만 리뷰를 드리다보니 제 의도를 전달하는데 한계가 있을거에요. 한번 읽어보시고 이해가 안되는 부분이 있으시다면 제게 찾아와주세요! 저랑 같이 논의해 보아요 :)

---

- README를 깔끔하게 작성하셨네요! 프로젝트를 파악하기 아주 편리하네요 ㅎㅎ

- https://github.com/MyNameSieun/Todo-List/blob/b46fe9be337a2b41f906784c0c65d6eae7077230/src/components/TodoItems.jsx#L17-L23 이 코드는 
  ```js
  const sortedTodos = [...todos].sort((a, b) => a.isDone - b.isDone);
  ```
  이렇게 줄여써봐도 좋을것 같아요. 
  
- https://github.com/MyNameSieun/Todo-List/blob/b46fe9be337a2b41f906784c0c65d6eae7077230/src/components/TodoItems.jsx#L12-L15 https://github.com/MyNameSieun/Todo-List/blob/b46fe9be337a2b41f906784c0c65d6eae7077230/src/components/TodoItems.jsx#L46-L51 이 부분은 이렇게도 쓸 수 있어요

  ```jsx
  const handleDeleteButtonClick = (id) => () => {
    const updatedTodos = todos.filter((todo) => todo.id !== id);
    setTodos(updatedTodos);
  }

  // .. 중략 ..  
  
  <div
    className="delete-box"
    onClick={handleDeleteButtonClick(item.id)}
  >
    x
  </div>

  ```
  
  반복분 내부에 사용되는 이벤트 핸들러 함수를 만들어 내는 함수인 handleDeleteButtonClick 작성해봤어요. 사용처에서는 item.id값을 넘겨서 호출하면, delete-box 요소가 클릭될 때 호출하는 함수를 반환해요. 이렇게 작성하면 조금 더 정리된 모습으로 이벤트 핸들러를 정의할 수 있어요.
  
  그리고, 리액트에서는 이벤트 핸들러 이름을 handleXxxXxx 와 같은 컨벤션으로 짓는 경향이 있어요. 이렇게 이름을 지으면 동료 개발자들이 함수의 역할에 대해 더 잘 파악할 수 있을것 같아요.
  
- https://github.com/MyNameSieun/Todo-List/blob/b46fe9be337a2b41f906784c0c65d6eae7077230/src/components/TodoItems.jsx#L29-L53 시간이 되신다면 이 부분을 컴포넌트로 분리하는 작업을 해보면 좋을것 같네요!

- 저는 TodoInput의 props를 조금 다르게 설계해보고 싶어요.
  ```jsx
  // TodoInput.jsx
  import React, { useState } from "react";
  
  /**
   * @param {{
   *   onSubmit: (newTask: string) => void
   * }} props
   */
  function TodoInput({ onSubmit }) {
    const [newTask, setNewTask] = useState("");
  
    const valueChangeHandler = (event) => {
      setNewTask(event.target.value);
    };
  
    const addClickBtnHandler = () => {
      if (newTask.trim() === "") {
        return;
      }
  
      setNewTask("");
      onSubmit(newTask);
    };
  
    return (
      <div className="todo-input">
        <input
          type="text"
          placeholder="Add your task"
          value={newTask}
          onChange={valueChangeHandler}
        ></input>
        <div className="add-box" onClick={addClickBtnHandler}>
          Add
        </div>
      </div>
    );
  }
  
  export default TodoInput;

  ```
  컴포넌트를 위의 모습으로 변경하면 그 사용처인 App.jsx는 이렇게 바꿀 수 있을것 같아요.
  
  ```js
  // App.jsx
  import React, { useState } from "react";
  import "./App.css";
  import TodoItems from "components/TodoItems";
  import TodoInput from "components/TodoInput";
  
  function App() {
    const [todos, setTodos] = useState([]);
  
    const today = new Date();
    const currentDate = today.toLocaleDateString("ko-KR", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  
    return (
      <body>
        <div className="main-layout ">
          <div className="todo-layout">
            <div className="todo-top">
              <div className="todo-info">
                {" "}
                <div className="todo-title">Todo-list 📆</div>
                <div className="todo-date">{currentDate}</div>
              </div>
  
              <div className="todo-tasks">{todos.length} tasks</div>
              <TodoInput
                onSubmit={(newTask) => {
                  const newTodo = {
                    id: todos.length + 1,
                    task: newTask,
                    isDone: false,
                  };
  
                  setTodos([...todos, newTodo]);
                }}
              />
            </div>
          </div>
          {/*  todos, setTodos를 TodoItems.jsx에 props로 전달 */}
          <TodoItems todos={todos} setTodos={setTodos} />
        </div>
      </body>
    );
  }
  
  export default App;

  
  ```

  이렇게 바꿔본 이유는, 기존에 setTodos함수를 TodoInput에 넘기는 것은 컴포넌트에게 불필요한 권한을 많이 준다고 생각했어요. TodoInput은 클릭했을 때만 상위 컴포넌트에게 데이터를 넘기면 되니까요. 그래서 onSubmit이라는 props를 만들어줬어요. Add 버튼을 클릭하면 양식 validation을 하고 문제가 없으면 부모에게 newTask를 넘겨주죠. 이제 값을 todos 상태에 추가하는건 부모컴포넌트의 몫이 되었네요.
  
  이렇게 바꾸고 보니 newTask 상태는 App에서는 안쓰고 TodoInput외에 쓰이는 부분이 없으니 TodoInput으로 옮겨줬어요. 그리고 id를 만들어내는 부분은 부모에게 있으니, todos로 props로 넘길 필요가 없게 되었네요.
  
  컴포넌트에게 전하는 props는 가능한 한 최소한의 데이터와 권한(데이터를 변경할 수 있는 함수의 범위)을 줘야한다고 생각해요. 불필요한 데이터, 너무 많은 권한을 전하면 컴포넌트의 역할이 비대해질 가능성이 아주크거든요. 그러면 장기적으로 관리하기가 어려울거에요.
  
  글로 쓴 설명이 제가 다시 읽어도 너무 어렵네요.. ㅋㅋ 궁금하시면 제게 찾아와주세요! 차분히 다시 설명 드려볼게요 :) 

- https://github.com/MyNameSieun/Todo-List/blob/b46fe9be337a2b41f906784c0c65d6eae7077230/src/components/TodoItems.jsx#L46-L51 https://github.com/MyNameSieun/Todo-List/blob/b46fe9be337a2b41f906784c0c65d6eae7077230/src/components/TodoInput.jsx#L28-L30 button 엘리먼트를 사용하면 좋을것 같네요!

**Comment by MyNameSieun** [comment]
감사합니다!
